---
name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        default: 'hml'
        type: choice
        options:
          - hml
          - prod
      confirm:
        description: 'Type "destroy" to confirm'
        required: true

jobs:
  destroy:
    name: Destroy ${{ github.event.inputs.environment }} infrastructure
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'destroy'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=destroy-plan

      - name: Terraform Destroy
        run: terraform apply destroy-plan

      - name: Cleanup summary
        run: |
          echo "## Destruction Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Environment: ${{ github.event.inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "- Status: Infrastructure destroyed successfully" >> $GITHUB_STEP_SUMMARY
          echo "- Timestamp: $(date)" >> $GITHUB_STEP_SUMMARY
